---
- hosts: all
  tasks:
    - name: Install git
      win_chocolatey:
        name: git
        state: present
    - name: Install multiple packages
      win_chocolatey:
        name:
        - procexp
        - putty
        - windirstat
        state: present