- name: Build Templates
  hosts: all
  tasks:
  - name: Build Windows 10
    docker_container:
      name: build-windows-10
      auto_remove: no
      image: maartenmol/dhs-packer
      command: ["packer build -force -var 'vcenter_pass=VD!fli9ht' -var-file 'vars_vcenter.json' Windows_10.json"]
  - name: Build Windows Server 2019
    docker_container:
      name: build-windows-server-2019
      auto_remove: no
      image: maartenmol/dhs-packer
      command: ["packer build -force -var 'vcenter_pass=VD!fli9ht' -var-file 'vars_vcenter.json' Windows_Server_2019.json"]
  - name: Build Windows Server 2019 CORE
    docker_container:
      name: build-windows-server-2019-core
      auto_remove: no
      image: maartenmol/dhs-packer
      command: ["packer build -force -var 'vcenter_pass=VD!fli9ht' -var-file 'vars_vcenter.json' Windows_Server_2019_Core.json"]
  - name: Build CentOS 8
    docker_container:
      name: build-centos-8
      auto_remove: no
      image: maartenmol/dhs-packer
      command: ["packer build -force -var 'vcenter_pass=VD!fli9ht' -var-file 'vars_vcenter.json' CentOS_8.json"]