---
- name: Deploy VM from Template
  hosts: all
  gather_facts: no
  tasks:
    # Deploy a VM from a template using Ansible 'vmware_guest' module
    - name: Deploy VM from template
      vmware_guest:
        hostname: 172.27.72.3
        username: administrator@vsphere.local
        password: VD!fli9ht
        validate_certs: no
        datacenter: Flightcase
        cluster: DHSNEXT
        #resource_pool: '{{ deploy_vsphere_resourcepool }}'
        folder: /KlantXYZ
        name: '{{ inventory_hostname }}'
        state: poweredon
        annotation: "{{ guest_notes }}"
        disk:
        - size_gb: 100
          type: thin
          datastore: '{{ deploy_vsphere_datastore }}'
        networks:
        - name: FlightCase Network
          type: static
          ip: '{{ guest_custom_ip }}'
          netmask: 255.255.255.0
          gateway: 172.27.72.1
          dns_servers:
          - 172.27.72.4
        hardware:
          memory_mb: 4096
          num_cpus: 2
          num_cpu_cores_per_socket: 2
        customization:
          autologon: yes
          password: P@ssword
          dns_suffix: dhsnext.nl
          dns_servers:
          - 172.27.72.4
          hostname: '{{ inventory_hostname }}'
          orgname: KlantXYZ
        template: Windows2019-Template
        wait_for_customization: yes
        wait_for_ip_address: yes
      delegate_to: localhost
    - name: Install multiple Windows packages
      when: ansible_facts['os_family'] == "Windows"
      win_chocolatey:
        name:
        - notepadplusplus
        - git
        - windirstat
        - openssh
        state: present
    - name: Install the Kaseya Agent (Test nextGoud)
      when: ansible_facts['os_family'] == "Windows"
      win_package:
        path: https://nextbeheer.dhs.nl/mkDefault.asp?id=91218921
        product_id: 'KADHSNF983289444115196'
        arguments: /e /c /g=root.test_nextgoud /s
    - name: Download Kaseya for Linux
      when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"
      get_url:
        url: https://nextbeheer.dhs.nl/mkDefault.asp?id=84214887
        force: no
        dest: /opt/KccAgent.sh
        mode: '0755'
    - name: Run Kaseya for Linux Installer
      when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"
      shell: /opt/KccAgent.sh